// FactoryNote core types — 도메인별 barrel. harness-agnostic(Layer 1-2).
export type {
	ArtifactFormat,
	ChatMessage,
	Comment,
	GateDecision,
	GateVerdict,
	HistoryEntry,
	StageId,
	StageKind,
	ValidThrough,
} from "./gate.ts";
export type {
	AgentRole,
	AgentSpawn,
	ArtifactPaths,
	ChildToolBudget,
	ChildTurnBudget,
	DesignFeedbackDirective,
	DesignFeedbackPhase,
	FeedbackAgent,
	FeedbackAxis,
	FeedbackAxisOutcome,
	FeedbackCapability,
	FeedbackLevel,
	FeedbackOutcome,
	SpawnOptions,
} from "./feedback.ts";
export type {
	GraphFileNode,
	GraphFlowchartEdge,
	GraphFlowchartFile,
	GraphFlowchartNode,
	GraphFlowchartShape,
	GraphKind,
	GraphLevel,
	GraphLevelFile,
	GraphRef,
	GraphSequenceFile,
	GraphSequenceFragment,
	GraphSequenceItem,
	GraphSequenceMessage,
	GraphSequenceParticipant,
	GraphTreeNode,
} from "./graph.ts";
export type { PipelineState } from "./pipeline.ts";
