// static 역량 feedback 에이전트 정의(24개) — tools: read/write/bash.
// 단일 진실은 feedback-agents.ts 의 FEEDBACK_AGENTS 조합. 이 파일은 데이터만.
// 타입은 types/feedback.ts 에서 — 이 파일이 레지스트리(feedback-agents.ts)를
// 역참조하면 순환의존이 생긴다(2026-08 하드닝으로 해체됨).
import type { FeedbackAgent } from "./types/feedback.ts";

export const FEEDBACK_AGENTS_STATIC: readonly FeedbackAgent[] = [
	{
		name: "completeness",
		focus: "누락·범위·숨겨진 가정",
		checklist: [
			"요구사항/작업이 누락 없이 망라되었는가?",
			"범위 밖·숨겨진 가정이 명시되었는가?",
		],
		capability: "static",
		stages: [1, 2, 3],
	},
	{
		name: "clarity",
		focus: "모호함·주관적 표현",
		checklist: ["모호한 단어·해석 여지·주관적 표현이 없는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "traceability",
		focus: "시나리오↔요구사항 연결",
		checklist: [
			"각 시나리오가 승인된 요구사항에 연결되며 정상 경로가 빠짐없이 covered되는가?",
		],
		capability: "static",
		stages: [1],
	},
	{
		name: "consistency",
		focus: "요구사항 간 충돌/모순",
		checklist: ["요구사항/명세 간 충돌·모순이 없는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "measurability",
		focus: "검증가능·측정가능 acceptance",
		checklist: ["각 요구사항이 검증 가능한 acceptance 기준을 갖는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "scope-boundaries",
		focus: "비범위 명시·범위 확장 억제",
		checklist: ["명시적 비범위(out of scope)가 있고 범위 확장이 억제되었는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "edge-error-scenarios",
		focus: "예외/오류/경계 시나리오",
		checklist: ["예외·오류·경계(빈 입력·실패·중복) 시나리오가 covered되는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "nonfunctional",
		focus: "NFR(성능/접근성/보안) 명시",
		checklist: ["비기능 요구사항(성능·접근성·보안 등)이 명시되었는가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "user-value",
		focus: "사용자 가치·MVP 적합성",
		checklist: ["사용자 가치가 명확하고 MVP 범위로 적합한가?"],
		capability: "static",
		stages: [1],
	},
	{
		name: "extensibility",
		focus: "확장 포인트·확장성 영향",
		checklist: [
			"미래 확장 포인트와 확장성·유지보수 영향이 참고용으로 명시되었는가?",
		],
		capability: "static",
		stages: [1, 2],
	},
	{
		name: "cohesion-coupling",
		focus: "응집/결합·단일 책임",
		checklist: ["모듈/클래스가 단일 책임이고 응집되며 결합이 최소인가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "layering-architecture",
		focus: "계층 분리·의존 방향",
		checklist: ["계층 분리·의존 방향·아키텍처 패턴이 적합한가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "oo-principles",
		focus: "SOLID·과잉 추상화",
		checklist: ["객체지향 원칙에 부합하고 과잉 추상화가 없는가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "scalability-performance",
		focus: "병목·확장성·성능 설계",
		checklist: ["병목·확장성·성능 설계가 적절한가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "data-model",
		focus: "데이터/상태 모델",
		checklist: ["데이터/상태 모델이 명확하고 상태 변경 경로가 명확한가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "api-surface",
		focus: "공용 API·인터페이스",
		checklist: ["공용 API가 최소이고 인터페이스 설계가 적절한가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "testability",
		focus: "테스트 용이 설계",
		checklist: ["테스트하기 쉬운 구조(seam/의존 주입)인가?"],
		capability: "static",
		stages: [2],
	},
	{
		name: "correctness-order",
		focus: "구현 순서·의존성 존중",
		checklist: ["구현 순서가 의존성을 존중하는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "integration-seams",
		focus: "통합 지점·인터페이스 계약",
		checklist: ["통합 지점·인터페이스 계약이 명시되었는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "verifiability-milestones",
		focus: "마일스톤 검증 가능",
		checklist: ["각 마일스톤이 검증 가능한 acceptance를 갖는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "effort-estimation",
		focus: "작업량 추정 현실성",
		checklist: ["작업량 추정이 현실적이고 병목 작업이 식별되었는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "rollback-reversibility",
		focus: "롤백/되돌리기 비용",
		checklist: ["롤백/되돌리기 비용·가능성이 고려되었는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "cicd-deployment",
		focus: "CI/CD·배포·환경",
		checklist: ["CI/CD·환경·배포 고려가 포함되었는가?"],
		capability: "static",
		stages: [3],
	},
	{
		name: "observability",
		focus: "로깅/모니터링/디버깅",
		checklist: ["로깅·모니터링·디버깅 고려가 포함되었는가?"],
		capability: "static",
		stages: [3],
	},
];
