// @factorynote/core entry point (barrel).
// M3 Persistence · M1 Stage Registry · Engine(상태기계). harness-agnostic(Layer 1-2).
export type {
	ArtifactFormat,
	AgentRole,
	AgentSpawn,
	ArtifactPaths,
	ChatMessage,
	ChildToolBudget,
	ChildTurnBudget,
	Comment,
	DesignFeedbackDirective,
	DesignFeedbackPhase,
	FeedbackAxis,
	FeedbackAxisOutcome,
	FeedbackLevel,
	FeedbackOutcome,
	GateDecision,
	GateVerdict,
	GraphFileNode,
	GraphFlowchartEdge,
	GraphFlowchartFile,
	GraphFlowchartNode,
	GraphFlowchartShape,
	GraphKind,
	GraphLevel,
	GraphLevelFile,
	GraphRef,
	GraphSequenceFile,
	GraphSequenceFragment,
	GraphSequenceItem,
	GraphSequenceMessage,
	GraphSequenceParticipant,
	GraphTreeNode,
	HistoryEntry,
	PipelineState,
	SpawnOptions,
	StageId,
	StageKind,
	ValidThrough,
} from "./types/index.ts";
export {
	STAGE_CATALOG,
	STAGE_KINDS,
	LEGACY_KINDS,
	feedbackProfileOf,
	isStageKind,
	stageDefAt,
	stageDefs,
} from "./stages.ts";
export type { StageDefinition, StageKindDefinition } from "./stages.ts";
export {
	FEEDBACK_AGENTS,
	FEEDBACK_TOOLS,
	feedbackMenuForStage,
} from "./feedback-agents.ts";
export type {
	FeedbackAgent,
	FeedbackCapability,
} from "./feedback-agents.ts";
export {
	atLoopCeiling,
	applyVerdict,
	initialState,
	isComplete,
	MAX_LOOPS,
	markArtifactReady,
	nextStageId,
} from "./engine.ts";
export {
	artifactPath,
	checkRequiredGraph,
	clearArtifactPrev,
	featureDir,
	invalidateArtifactsAfter,
	loadState,
	promoteGraphTree,
	readArtifact,
	readArtifactPrev,
	saveState,
	statePath,
	writeArtifact,
} from "./persistence.ts";
export {
	collectGraphChildFiles,
	coerceGraphFlowchartFile,
	coerceGraphLevelFile,
	coerceGraphSequenceFile,
	graphDirNameFor,
	graphKindOf,
	graphRefAttemptCount,
	graphRefFile,
	graphRefFiles,
	GRAPH_REF_RE,
	isSafeChildPath,
	isSafeGraphName,
	loadGraphTree,
	parseAnyGraphKind,
	parseGraphFlowchartFile,
	parseGraphLevelFile,
	parseGraphSequenceFile,
} from "./graph.ts";
export {
	CHILD_SPAWN_OPTIONS,
	DEFAULT_FEEDBACK_LEVEL,
	DEFAULT_MAX_LOOPS,
	FEEDBACK_LEVELS,
	MAX_REPORT_INPUT_CHARS,
	aggregateFeedback,
	clampReportInput,
	designRevisionTask,
	designTask,
	feedbackAgentTask,
	feedbackLevelCountSpec,
	nextDesignFeedbackStep,
	parseFeedback,
	runDesignFeedbackLoop,
} from "./orchestration.ts";
export type {
	DesignFeedbackReport,
	DesignFeedbackTransition,
} from "./orchestration.ts";
